version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: node index.js
    restart: unless-stopped
    volumes:
      - .:/home/node
      - ~/.ssh:/.ssh-localhost:ro

  nginx:
    depends_on:
      - node
    image: nginx:1.15
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  database:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./.dbdata:/data/db
